### ISSUE TITLE
Modify polygons instead of copying and creating new ones

### ISSUE THREAD

**Issue by adisidev** [mgastner/cartogram-cpp#121]
Currently we create new copies of polygons if we want to make changes to them (densify, project, simplify etc). It may be faster if simply modify them in place.

**Comment by nihalzp** [comment]
It seems that the current code for projection modifies the points in place without creating new copies of the polygon.

For densify and simplify operations, this might not be efficient. For densify, we would need to insert points in the middle of the polygon, and for simplify, we would need to remove some points from the middle of the polygon. Both operations would be O(n) in the worst-case scenario.
