### ISSUE TITLE
Use `.hpp` instead of `.h`

### ISSUE THREAD

**Issue by adisidev** [mgastner/cartogram-cpp#128]
Should we switch to naming our header files with `.hpp` instead of `.h`?
https://stackoverflow.com/questions/152555/h-or-hpp-for-your-class-definitions

Here is more on the topic. A lot of our header files do indeed include C++ specific syntax. Further, changing to `.hpp` allows editors to more easily automatically detect that the language is C++ rather than C.

**Comment by mgastner** [comment]
I agree. There is also some discussion here: https://www.quora.com/qemail/tc?al_imp=eyJ0eXBlIjogMzMsICJoYXNoIjogIjE0Mzg5NTE1MTU1NTgwNTI0Nzd8M3wxfDMxMDc3MDg0NyJ9&al_pri=1&aoid=zYNQNN1iiBD&aoty=2&aty=4&cp=3&et=2&id=851ffdc8705a43b0aa3ac42c8dc38b38&q_aid=IE0OmFBLOAZ&uid=b0shN5Yyy1A
