### ISSUE TITLE
Inability of code to read csv values formatted in categories other than General

### ISSUE THREAD

**Issue by edliau** [mgastner/cartogram-cpp#137]
Running the `cartogram` function will return an error stating "Areas must be numeric or NA" when the target CSV file has its data formatted in categories other than General under "Format cells..." Maybe the code can be changed to accept values such as "Numbers" and "Custom".

**Comment by mgastner** [comment]
I am uncertain what you mean. CSV files are plain-text files, so entries have no connotation of being "Numbers" or "General". Would you mind elaborating?

**Comment by edliau** [comment]
I've attached some images below to more clearly demonstrate how this issue can be reproduced. I think the main issue is when data is formatted with the "1000 separator(,)", Excel actually physically inserts these commas if the data is used as inputs for anything else. While most other formatting settings are typically lost upon closing the file due to its plain-text nature, Excel appears to retain these settings.

![Screenshot 2022-07-03 151714](https://user-images.githubusercontent.com/105198642/177029404-d1f1b887-2a4d-4814-be80-5d04c7866d80.jpg)
![Screenshot 2022-07-03 151852](https://user-images.githubusercontent.com/105198642/177029474-60c3175d-f447-4b5d-9aee-25820194b2b3.jpg)
