### ISSUE TITLE
Add a flag to enable and disable `weights` when assigning target density

### ISSUE THREAD

**Issue by adisidev** [mgastner/cartogram-cpp#200]
@mgastner I just wanted to check, are you still keen on this? I'm not sure if I can think of a potential use-case.

**Comment by mgastner** [comment]
Sorry, I don't remember the background to this issue. If convergence is no longer an issue in any of the unit tests, it's probably obsolete.

**Comment by adisidev** [comment]
We can introduce this flag if we need it again in the future.
