### ISSUE TITLE
Naming conventions for URLs

### ISSUE THREAD

**Issue by adisidev** [mgastner/cartogram-cpp#79]
Currently, URLs in our code that exceed 80 characters are split into two comments. However, this ends up making it tougher to copy paste and visit the URL, or open it directly using an editor. 

Indeed, the Google style guide for C++ to mentions that URLs can be above 80 characters:
https://google.github.io/styleguide/cppguide.html#Line_Length

This stackexchange post has some more discussion about it.
https://meta.stackexchange.com/questions/12527/do-i-have-to-worry-about-copyright-issues-for-code-posted-on-stack-overflow

Shall we perhaps consider merging the split URLs into one comment per URL?

**Comment by adisidev** [comment]
The issue with a URL shortening service is that it is may not always be a permalink, and it does not give context into where the link was taken off of.

**Comment by mgastner** [comment]
Okay, understood. We can add long URLs as an exception to our in-house 80-character rule.

**Comment by adisidev** [comment]
In that case, we already follow this rule, and this issue has been solved by our past selves!
