### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by mgastner** [mgastner/cartogram-cpp#92]
GitHub replaced the naming convention of the "default branch" in all new repositories. Changing the name from `master` to `main` is likely to reduce confusion in the future. Here are instructions: https://www.git-tower.com/learn/git/faq/git-rename-master-to-main

**Comment by mgastner** [comment]
`master` renamed to `main` on 11 March 2022.

**Comment by PeterNjeim** [comment]
Causing confusing while pretending you're reducing it. Shameful
