### ISSUE TITLE
Zero blur width causes bug in world map

### ISSUE THREAD

**Issue by mgastner** [mgastner/cartogram-cpp#97]
After the blur width hits zero, we observed that the maximum area error began increasing. The temporary fix, implemented by #93, is to keep the blur width above zero at all times. While it is a short-term fix, we must investigate the root cause of this bug.

**Comment by adisidev** [comment]
Is this still true after #167 ?
Nonetheless, this has been added as a TODO within the code, I think it is worth closing here, and maybe we can deal with it in #195
